const Parser = require('binary-parser').Parser
const cmmcParser = require('./_sensor_node')
const headerParser = require('./_header')
const tailParser = require('./_tail')

const parser = Parser.start()
  .nest('header', {type: headerParser})
  .endianess('little')
  .uint32('temperature_c')
  .uint32('humidity_percent_rh')
  .uint32('gas_resistance_ohm')
  .uint32('sound_avg_db')
  .uint32('max_acc')
  .uint32('acc_x')
  .uint32('acc_y')
  .uint32('acc_z')
  .uint32('gyro_x')
  .uint32('gyro_y')
  .uint32('gyro_z')
  .uint32('mag_x')
  .uint32('mag_y')
  .uint32('mag_z')
  .int32('nb_rssi')
  .uint32('nb_csq')
  .uint32('nb_ber')
  .int32('gps_latitude')
  .int32('gps_longitude')
  .int32('gps_altitude_cm')
  .int32('gps_us')
  .uint32('cnt')
  .uint32('battery_raw')
  .uint8('battery_percent')
  .nest('cmmc_packet', {type: cmmcParser})
  .nest('controller_tail', {type: tailParser})
  .nest('gateway_tail', {type: tailParser})

module.exports = parser
